version: "3.8"

services:
  backend:
    build: ./backend
    container_name: gardeau_backend
    ports:
      - "8000:8000"
    restart: unless-stopped

  web:
    image: nginx:alpine
    container_name: gardeau_web
    ports:
      - "8080:80"
    volumes:
      - ./:/usr/share/nginx/html:ro
    depends_on:
      - backend
    restart: unless-stopped
